firebase/quickstart-js

auth/facebook-redirect.html
=> Fix Facebook auth redirect sample

database/README.md, database/index.html, database/main.css, database/scripts/main.js, storage/README.md, storage/index.html
Changed 'stared' to 'starred' and added more clear instructions for copying the initialization snippet
=> Fix misspelled "starred" and added better instructions

database/scripts/main.js
- Fixes the transaction logic for stars (need to handle the case if the transaction object is null)
- Fixed logic where the incorrect UID was used in ref
Fixes #14
=> Fixes Add star transaction logic and ref

database/scripts/main.js
This is a new PR, please close the other one. Thank you.
=> Issue #24 Google profile photo patch new

database/index.html, database/main.css, database/scripts/main.js
Resolves #23 by creating a log out button for the database project. This will be useful to those who would like users to log in and be able to log out. I tried to follow the pattern for the rest of the project by creating a button and binding an event listener. Because of the way posts are added to the page, logging out and logging back in has some interesting consequences (posts get added again and again), but I think this is a nice solution without a major refactor in order to fix that.
=> feat(log out): Adding log out button to database project

storage/index.html
Now using the Promise instead of the event watcher for Storage.
=> Switch to a Promise for watching upload completion of storage sample.

auth/chromextension/README.md, auth/chromextension/background.html, auth/chromextension/background.js, auth/chromextension/credentials.js, auth/chromextension/manifest.json
Also changed e behavior so that we can sign out.
=> Added a background page in the chrome extension sample 

database/scripts/main.js
Post can handle child_changed, child_removed event not only child_added, like comment
=> Post can handle child_changed, child_removed event not only child_added

database/scripts/main.js
Hi, I find this issue and fix it.
I hope this is useful.
=> Fix Sign out and then sign in screen does not respond. (database/)

messaging/README.md
Enable show message icon with correct filename
=> Modify icon filename

database/scripts/main.js
This will allow users who's username subproperty isn't specified to have a working username.
=> Allow username to fallback to email

firestore/firestore.rules
This should fix the issue #165 with correct security rules to run the project.
=> Security rules based on quickstart-ios firestore

firestore/scripts/FriendlyEats.Data.js
filters.price != "Any" will always be TRUE which will then overwrite all other filters
=> Fix demo app filtering issue -  Update FriendlyEats.Data.js

.opensource/project.json, README.md
Improve rendering on this page:
https://firebaseopensource.com/projects/firebase/quickstart-js/
=> Configure for firebaseopensource.com

messaging/firebase-messaging-sw.js, messaging/index.html
Update the version of the SDK used by the messaging sample.
=> Bump messaging versions to 4.8.1

.gitignore, firestore/index.html, firestore/scripts/FriendlyEats.js, firestore/styles/main.css
Fixes #238,
Fixes #236 
Fixes #230
=> Fix issues #238, #236, #230

firestore/README.md
I tried this introduction for learning purposes about Firebase and its databases and stumbled over that point
=> Update for the current Firebase-App Version

auth/README.md
Adds instructions on how to deploy quickstart sample app to Firebase Hosting production.
=> Adds instructions on how to deploy quickstart Auth sample app

firestore/scripts/FriendlyEats.Mock.js
Otherwise, both numRating and numRatings are created in the database,
leading to the average rating being NaN.
=> Fix typo affecting ratings

auth/chromextension/README.md
- The sample link has been updated to reference the
new url path that the chrome web store enforces.
- Note that thhe actual extension is the same leveraging
the ID of: ehflheedljfngcklcnigfonmllgkadbb
=> Update Chrome Extension Sample Link

CONTRIBUTING.md
I don't see gulpfiles in the samples
=> Remove `gulp` step from CONTRIBUTING.md

firestore/scripts/FriendlyEats.Data.js, firestore/scripts/FriendlyEats.View.js
resolves #211 
Restaurant cards on the home page listen for updates and their star count changes as new ratings come in.
=> Make restaurant ratings on the homepage realtime

firestore/README.md
=> Add mention of offline persistence to README

auth/README.md
=> Add step to set up support email

.eslintrc.json, messaging/firebase-messaging-sw.js, messaging/index.html
This makes the messaging sample more consistent with the docs.
Fixes #325
As part of this, I updated the whole repo's eslint file to support es2017.
=> Messaging: Convert from var to const

firestore/scripts/FriendlyEats.Data.js
Use the correct function syntax to allow `this` references to work.
=> Correct syntax for this usage

auth/main.css, auth/multi-tenant-ui.html
added quickstart for multi-tenant beta
=> added quickstart for multi-tenant beta

auth/apple-popup.html, auth/apple-redirect.html, auth/index.html
Created Apple Auth samples. They are based on `microsoft-popup.html` and `microsoft-redirect.html`.
=> Sign in with Apple: add popup and redirect samples

auth/email-password.html
Fixes https://github.com/firebase/quickstart-js/issues/371
=> Update comment to correctly refer to user creation (Fixes: #371)

config/README.md, config/index.html, config/main.css
Add Firebase Remote Config web Sample.
=> Add RC sample

messaging/README.md
=> Add warning about background behavior of FCM

auth/main.css
missing parenthesis in auth/main.css added at line 163 closing the keyframes block
=> missing parenthesis added

messaging/.eslintrc.json, messaging/firebase-messaging-sw.js, messaging/index.html
Update FM Web QS. Specifically 
- Removed onTokenRefresh (no-op)
- Updated sw to use onBackgroundMessage
- Fixed a minor typo
- Add single quote eslint check
=> 2020 api update

database/scripts/main.js
See cl/343507198 
These were moved to snippets-web
=> Remove DB snippets

functions/public/scripts/main.js
See: https://github.com/firebase/snippets-web/pull/63
Googlers: this is safe once http://cl/345334564 is submitted
=> Remove callable functions snippets

remote-config/index.html
See: https://github.com/firebase/snippets-web/pull/68
Googlers: this is safe after http://cl/346563460
=> Remove Remote Config snippets

auth/apple-popup.html, auth/apple-redirect.html, auth/email-password.html, auth/facebook-credentials.html, auth/facebook-popup.html, auth/facebook-redirect.html, auth/github-popup.html, auth/github-redirect.html, auth/google-popup.html, auth/google-redirect.html, auth/microsoft-popup.html, auth/microsoft-redirect.html, auth/phone-invisible.html, auth/phone-simple-popup.html, auth/phone-visible.html, auth/twitter-popup.html, auth/twitter-redirect.html
=> Remove almost all remaining auth snippets

messaging/index.html
Substituting new method per Arthur's instructions and internal bug 166101751.
Thanks!
=> Update deprecated method.

firestore/README.md, firestore/index.html, firestore/package.json, firestore/scripts/FriendlyEats.Mock.js
Googlers: for context see http://b/176971059
=> Cloud Firestore --> Firestore

messaging/firebase-messaging-sw.js
Solution for https://github.com/firebase/firebase-js-sdk/issues/4412 and https://github.com/firebase/quickstart-js/issues/495
=> Add notification customization info

.github/workflows/test.yml, firestore/package-lock.json, lerna.json, package-lock.json, package.json
- Update workflows to use current Node LTS (18)
- Update actions to latest versions (checkout, setup-node, cache)
- Update deps
=> Update repo infra

messaging/index.html
This makes the quick start compatible with Safari Webpush. More [here](https://docs.google.com/document/d/1lsPskjlQVjGVvJe6WjFbsnSBIK1qxOIymVaD-hznPug/edit?resourcekey=0-NyiPlpSrU1-qbB0Q9AyUXg#)
=> Display Request Div to make JS quick start compatible with Safari

messaging/.gitignore, messaging/.prettierrc, messaging/config.ts, messaging/firebase.json, messaging/index.html, messaging/main.ts, messaging/package-lock.json, messaging/package.json, messaging/tsconfig.json, messaging/vite.config.js
Since Firebase Messaging uses service workers as well as notification permissions, and these are only available in secure contexts AKA https, this example only works on Firebase Hosting, and not through `firebase serve` or `vite`
=> feat(messaging): Migrate to Vite + TS

.gitignore, .idx/dev.nix, .vscode/settings.json, dataconnect/.idx/dev.nix, dataconnect/.vscode/settings.json, dataconnect/app/src/lib/firebase.idx.tsx, dataconnect/app/src/vite.config.idx.ts, dataconnect/app/vite.config.idx.ts, dataconnect/idx-template.json, dataconnect/idx-template.nix
<a href="https://idx.google.com/new?template=https%3A%2F%2Fgithub.com%2Fdavideast%2Fquickstart-js%2Ftree%2Fmaster%2Fdataconnect">
<picture>
<source
media="(prefers-color-scheme: dark)"
srcset="https://cdn.idx.dev/btn/open_dark_32.svg">
<source
media="(prefers-color-scheme: light)"
srcset="https://cdn.idx.dev/btn/open_light_32.svg">
<img
height="32"
alt="Open in IDX"
src="https://cdn.idx.dev/btn/open_purple_32.svg">
</picture>
</a>
=> Data Connect IDX template

dataconnect/README.md
This should fix the URL for the Cloud console and correct the product name "Data Connect"
=> docs: update dataconnect/README.md

dataconnect/README.md
Small PR - adjusts the license reference in `dataconnect/README.md`.
=> Update license reference

ai/ai-react-app/package.json, ai/ai-react-app/yarn.lock
=> [FirebaseAI] Bump to v12
