storage/index.html

Currently each upload overwrite the same file called `images`.
I think this behavior is not expected.
Each file will be upload to the folder `images` and is called like the `file.name` from the hdd.
This PR fix https://github.com/firebase/quickstart-js/issues/6 too

Fix overwrite same file.

---

database/index.html

Remove the defer attribute from Material Design Lite library script element so It can work fine.
Please refer to the following issue.
[https://github.com/firebase/quickstart-js/issues/46](https://github.com/firebase/quickstart-js/issues/46)

Remove the defer attribute

---

messaging/firebase-messaging-sw.js

This should fix #70 
This was a bug I caught too late on to get in the 3.5.0 release but was fixed in 3.5.1 and above.
Should this sample code have the firebase version just marked as X.X.X with a todo comment? or is using a static version ok?
cc @kroikie

Bump firebase version in messaging SW

---

auth/index.html
messaging/index.html

Several `index.html` files fail HTML5 validation. I'd be inclined to remove the `/` in the `meta` tags altogether but, being unsure about the conformance requirements for this codebase, adding a space seemed the least intrusive approach.

Correct meta tag

---

database/README.md
storage/README.md

Image links in README.md are broken when viewed with a local markdown editor. Changing them to relative links fixes the problem and they still work fine on GitHub.

Fix image links to be relative

---

messaging/README.md
messaging/firebase-messaging-sw.js
messaging/firebase.json
messaging/index.html

This basically allows to run the sample simply with `firebase serve --project <projectid>` without having to configure the sample with project specific values both in the index.html and s=the service workers file.
The change is a bit tricky though because you were using the Firebase initialization in the service workers script as an include in the docs and we should probably still show the non-implicit way of configuring the SDK in the docs so I've worked around it by moving the non-implicit include within a comment.

Use Implicit Firebase initialization in the FCM sample.

---

firestore/README.md

I encountered an error upon deploying Firestore security rules before enabling the Cloud Firestore on my Firebase project.
```
Error: HTTP Error: 400, Project 'quickstart-js-firestore' is not a Firestore enabled project.
```
I think this additional step will help others avoid what I experienced.

add: Enable Cloud Firestore step

---

messaging/README.md

The part about replacing **VAPID KEY** was not described in the documentation which causes problems with quick start with testing firebase cloud messaging. I find many issues and problems on the web. 
I had the same problem too so I add steps in instruction in **README**.

Add missing part in documentation for messaging

---

messaging/index.html

added comments and excluded more lines
The samples in [this section](https://firebase.google.com/docs/cloud-messaging/js/client#retrieve-the-current-registration-token) include extra lines of code that aren't necessary to get a barebones sample running. It's also confusing to new developers (per #275) whether the functions in there are part of the Firebase SDK or functions that need to be implemented.

Clarify samples used in the FCM docs

---

firestore/scripts/FriendlyEats.js
messaging/index.html

Including `timestampsInSnapshots` now causes this warning to show up in the console:
> @firebase/firestore: Firestore (5.9.2): 
The timestampsInSnapshots setting now defaults to true and you no
longer need to explicitly set it. In a future release, the setting
will be removed entirely and so it is recommended that you remove it
from your firestore.settings() call now.

Update firestore settings

---

auth/chromextension/README.md
auth/chromextension/credentials.js
auth/facebook-credentials.html
auth/google-credentials.html

In Firebase V6, signInAndRetrieveDataWithCredential will be deprecated in favor of signInWithCredential. Replace them in the sample apps.

replaced APIs that to be deprecated with the new ones

---

messaging/index.html

Part of `messaging.requestPermission` deprecation: https://github.com/firebase/firebase-js-sdk/pull/1791

Use Notification.requestPermission instead of messaging.requestPermission

---

messaging/index.html

Modernizing our Messaging example. Developers don't use function declarations in callbacks anymore.

Use arrow functions in callbacks

---

.travis.yml
firestore/package-lock.json
package-lock.json
package.json

TravisCI builds are failing for about a week.
https://travis-ci.org/firebase/quickstart-js/builds
According to the error message, tests are failing because the version of Node.js is too old and can't parse spread operator. 
```
$ ./scripts/test.sh
/home/travis/.nvm/versions/node/v7.10.1/lib/node_modules/eslint/lib/cli-engine/cli-engine.js:257
...calculateStatsPerFile(messages)
^^^
SyntaxError: Unexpected token ...
```
It will be fixed by using LTS version of Node.js in Travis CI.
In this PR I wrote `node_js: 'lts/*'` in travis.yml.

Fix tests failing in Travis CI

---

functions/functions/package.json

When I run `firebase deploy` following the instruction in README.md, I got an error like this:
```
functions git:master ✶ ✩  ❯ firebase deploy
=== Deploying to 'quickstart-js-XXXXX'...
i  deploying database, functions, hosting
Running command: npm --prefix "$RESOURCE_DIR" run lint
> functions@ lint /Users/amagi/src/github.com/firebase/quickstart-js/functions/functions
> eslint .
✔  functions: Finished running predeploy script.
i  database: checking rules syntax...
✔  database: rules syntax for database quickstart-js-XXXXX is valid
Error: There was an error reading functions/package.json:
Engines field is required but was not found in functions/package.json.
To fix this, add the following lines to your package.json:
"engines": {
"node": "8"
}
⌚︎ 9s
```
So I added `engines` field to …

Fix engines missing in functions/functions

---

auth/chromextension/README.md

"Try out a demo version" section links to a Chrome extension on the Chrome Web Store that I un-published today. This change removes the section about a demo.
#285 Earlier this year the [original demo](https://chrome.google.com/webstore/detail/lpgchdfbjddonaolofeijjackhnhnlla) URL got replaced.
🚨 Both links are currently broken. If you have another demo hosted somewhere you can use that URL instead.

Remove link to demo on Chrome Web Store

---

messaging/README.md

fixes #413 
If a web app isn't registered before running the messaging quickstart, the code will crash because it is missing the `appId` field in the firebase config object.

Add create web app step to messaging

---

auth/README.md

chromeextension -> chromextension
`404`
https://github.com/firebase/quickstart-js/blob/master/auth/chromeextension
->
`200`
https://github.com/firebase/quickstart-js/tree/master/auth/chromextension

fix typo: auth/README

---

messaging/firebase-messaging-sw.js

Update the FCM service worker setup code to work with >=7.0.0 Firebase JavaScript SDK. There was a major change in `v7.0.0` as mentioned in the [release notes](https://firebase.google.com/support/release-notes/js#version_700_-_september_26_2019).
The same has been also acknowledged in this [firebase-js-sdk](https://github.com/firebase/firebase-js-sdk/issues/2287#issuecomment-553860831) issue.
PS - I am not sure if the comment I have updated in this PR is used to render the [official firebase.google.com docs](https://firebase.google.com/docs/cloud-messaging/js/receive#handle_messages_when_your_web_app_is_in_the_foreground) but looking at the metadata around the comment and noticing that `firebase.google.com`code block links to this commented code, I am guessing that's the case.

Fix FCM service worker setup code for >= 7.0.0.

---

auth/anon.html
auth/apple-popup.html
auth/apple-redirect.html
auth/chromextension/credentials.js
auth/customauth.html
auth/email-link.html
auth/email-password.html
auth/facebook-credentials.html
auth/facebook-popup.html
auth/facebook-redirect.html
auth/github-popup.html
auth/github-redirect.html
auth/google-credentials.html
auth/google-popup.html
auth/google-redirect.html
auth/microsoft-popup.html
auth/microsoft-redirect.html
auth/twitter-popup.html
auth/twitter-redirect.html

See:
- https://github.com/firebase/snippets-web/pull/57
- https://github.com/firebase/snippets-web/pull/58
As part of the move to the new JS SDKs it will be *much* easier if all of the snippets are in `snippets-web`, so I am going to start migrating them.

Remove auth snippets, move to snippets-web

---

database/scripts/main.js
messaging/firebase-messaging-sw.js
messaging/index.html
storage/index.html

This is the final move of snippets from quickstart-js to snippets-web
See:
https://github.com/firebase/snippets-web/pull/86
The only snippets which remain here are:
* Google and Facebook Auth snippets which are in HTML and not related to the Firebase SDK
* Some functions snippets which should probably be in snippets-node or functions-samples

Remove remaining snippet tags

---

messaging/manifest.json

instruction per https://webkit.org/blog/13878/web-push-for-web-apps-on-ios-and-ipados/

Add `standalone` config so the qucikstart is compatible with iOS & padOS Safari

---

firestore/angular-rewrite/package.json

Quick change to add the `--ui` flag to scripts that run the Firebase Emulators so that the Emulator Suite UI will be available on `localhost:4000`.

Added UI flag to Emulator Scripts

---

firestore/angular-rewrite/.gitignore
firestore/angular-rewrite/.vscode/launch.json

This PR adds a `launch.json` file  to the `.vscode/` directory to allow the quickstart to be launched from the debug window in vscode. Additionally, the `.gitignore` was modified to allow visibility into the `.vscode/` directory.

FriendlyEats `launch.json` file

---

firestore/src/app/submit-review-modal/submit-review-modal.component.ts

This PR removes a redundant injection of the `MatDialogData` and `MatDialogRef`  in the `submit-review-modal.component.ts` file.

Quick Fix for Angular DI

---

vertexai/main.ts

Update model name to `gemini-1.5-flash-preview-0514` as the previous preview model name may be phased out soon.

Update model names to use gemini-1.5-flash-preview-0514

---

firestore/package.json

Wrap the script argument of `firebase emulators:exec` command.
Related issue https://github.com/firebase/firebase-tools/issues/7476
On a Windows machine, when running the command below, the emulators do not start
```
firebase --project demo-friendly-eats emulators:exec --import ./app-data-seed --ui 'ng serve'
```
Might be related to how Windows treats single quotes https://stackoverflow.com/a/51090074.
Running the command below, emulators were able to start:
```
firebase --project demo-friendly-eats emulators:exec --import ./app-data-seed --ui "ng serve"
```

Wrap emulator exec script in double quotes

---

scripts/test.sh

Tests began failing after the introduction of `dataconnect/app/src/lib/dataconnect-sdk` in https://github.com/firebase/quickstart-js/pull/835, since that code does not comply with ESLint rules. I believe this is the generated dataconnect SDK, so instead of fixing the linting issues I think we should just not run ESLint against this generated code. Very open to other suggestions for fixing this- I'm looking to unblock CI failing on all branches.

Do not run ESLint in `dataconnect-sdk`

---

vertexai/main.ts
vertexai/package-lock.json
vertexai/package.json

- Upgrade Firebase from v10 to v11
- Use `firebase/vertexai` instead of `firebase/vertexai-preview`
- Upgrade Node and NPM version requirements
- Use non-preview model (?)

Upgrade Vertex AI in Firebase sample to v11

---

auth/index.html

MFA was implemented in [auth/mfa-password.ts](https://github.com/firebase/quickstart-js/blob/master/auth/mfa-password.ts) and [auth/mfa-password.html](https://github.com/firebase/quickstart-js/blob/master/auth/mfa-password.html), but there is currently no link to the MFA page.
Adding a link to mfa-password.html in auth/index.html so that users access the mfa page from the main page.

Add MFA link to the main page

---

ai/ai-react-app/src/components/Layout/LeftSidebar.module.css
ai/ai-react-app/src/components/Layout/LeftSidebar.tsx
ai/ai-react-app/src/components/Layout/MainLayout.tsx
ai/ai-react-app/src/config/personas.ts

Partnered with Gemini CLI to add Persona support to demonstrate system instructions:

Add persona selection to AI qs

---

.github/workflows/firebase-ai-check.yml
ai/ai-react-app/package.json
ai/ai-react-app/src/App.tsx
ai/ai-react-app/src/components/Layout/LeftSidebar.tsx
ai/ai-react-app/src/components/Layout/MainLayout.tsx
ai/ai-react-app/src/services/firebaseAIService.ts
ai/ai-react-app/src/views/LiveView.module.css
ai/ai-react-app/src/views/LiveView.tsx
ai/ai-react-app/yarn.lock

Add a new entry in the right sidebar that allows users to use the Live Audio Conversation (`startAudioConversation()`) API.

Add Live to Firebase AI sample app
